{% set name = "bloatectomy" %}
{% set version = "0.0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4f84db2264a3e337b13bde94c1154e1e46f9efaa3c501b26b5ee67f095f73363
  MD5: 70c8f9c9b0bab52544cda810b2d4f89c
  BLAKE2-256: c0371a9565a8d7693c8219e5419830939f0e1f06711d4da7baf86f71418a069f

build:
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - setuptools
    - python
  run:
    - python

test:
  imports:
    - bloatectomy
  source_files:
    - tests

about:
  home: "https://github.com/MIT-LCP/bloatectomy"
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "Bloatectomy: a method for the identification and removal of duplicate text in the bloated notes of electronic health records and other documents."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - 1fmusic
    - katerdowdy
